pipeline {
  agent { label 'maven-persistent' }
  options {
    buildDiscarder(logRotator(numToKeepStr: '5'))
    timeout(time: 10, unit: 'MINUTES')
  }
  stages {
    stage('Build App') {
      steps {
        withMaven(mavenSettingsConfig: 'openshift-registry') {
          sh "mvn clean compile jib:build"
        }
      }
    }
  }
}
