
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    metrics:
      enable: true
      #sensitive: false
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
