
management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: "/api/actuator"
  endpoint:
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
