pipeline {
  agent { label 'buildnode' }
  options {
    buildDiscarder(logRotator(numToKeepStr: '5'))
    timeout(time: 10, unit: 'MINUTES')
  }
  environment {
    M2_HOME = tool('maven35')
    PATH = "${M2_HOME}/bin:$PATH"
  }
  stages {
    stage('Build App') {
      steps {
        withMaven(mavenSettingsConfig: 'openshift-registry') {
          sh "mvn package fabric8:build"
        }
      }
    }
  }
}
