pipeline {
  agent { label 'buildnode' }
  options {
    buildDiscarder(logRotator(numToKeepStr: '5'))
    timeout(time: 10, unit: 'MINUTES')
  }
  environment {
    M2_HOME = tool('maven35')
    PATH = "${M2_HOME}/bin:$PATH"
    OPENSHIFT_LOGIN = credentials('dtschan-registry')
  }
  stages {
    stage('Build App') {
      steps {
        withMaven {
          sh "mvn clean package"
        }
      }
    }
    stage('Build Image') {
      steps {
        script {
          sh "mvn fabric8:build -Dfabric8.masterUrl=https://ose3-master.puzzle.ch:8443 -Dfabric8.namespace=dtschan -Dfabric8.password=${OPENSHIFT_LOGIN_PSW}"
        }
      }
    }
  }
}
